apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-k8s-stack
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-k8s-stack:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: nginx-k8s-stack
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-k8s-stack
  namespace: default
spec:
  serviceAccountName: nginx-k8s-stack
  stack: dev
  projectRepo: https://github.com/pulumi/examples
  repoDir: /kubernetes-ts-nginx
  branch: "refs/heads/master"
  refresh: true
  continueResyncOnCommitMatch: false
  resyncFrequencySeconds: 60
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.134.1-nonroot

